#!/bin/bash
while read -r node; do {
    let count=0
    ok=true
    validator=false
    until curl --http0.9 -sHf http://$node/testnet > /dev/null; do {
        echo "eth: beacon-setup node $node not ready, waiting..."
        sleep 10
        let count++
        [ $count -gt 60 ] && {
            echo "eth: connection to beacon-setup node $node failed too many times, skipping."
            ok=false
            break
        }
    }; done
    ($ok) && {
        validator=false
        bootnode=true
        ($validator) && {
            curl --http0.9 -s http://$node/eth-2 > /tmp/eth.tar.gz
            tar -xzvf /tmp/eth.tar.gz -C /tmp
        }
        ($bootnode) && {
            curl --http0.9 -s http://$node/bootnode > /tmp/bootnode.tar.gz
            tar -xzvf /tmp/bootnode.tar.gz -C /tmp
        }
        curl --http0.9 -s http://$node/testnet > /tmp/testnet.tar.gz
        tar -xzvf /tmp/testnet.tar.gz -C /tmp
        lighthouse boot_node --testnet-dir /tmp/local-testnet/testnet --port 30305 --listen-address 10.101.0.72 --disable-packet-filter --network-dir /tmp/local-testnet/bootnode &
        lighthouse --debug-level info bn --datadir /tmp/local-testnet/eth-2 --testnet-dir /tmp/local-testnet/testnet --enable-private-discovery --staking --enr-address 10.101.0.72  --enr-udp-port 9000 --enr-tcp-port 9000 --port 9000 --http-address 10.101.0.72 --http-port 8000 --http-allow-origin "*" --disable-packet-filter --target-peers 5 --execution-endpoint http://localhost:8551 --execution-jwt /tmp/jwt.hex &
        
        
        
        
    }
}; done < /tmp/beacon-setup-node



