version: '3.4'
services:
    39e016aa9e819f203ebc1809245a5818:
        build:
            context: .
            dockerfile: dummies/39e016aa9e819f203ebc1809245a5818
        image: 39e016aa9e819f203ebc1809245a5818

    f1d53a66de3c35d8a921558f3b4bdbbd:
        build:
            context: .
            dockerfile: dummies/f1d53a66de3c35d8a921558f3b4bdbbd
        image: f1d53a66de3c35d8a921558f3b4bdbbd

    # === 数据库服务 ===
    hnode_101_host3:
        build: ./hnode_101_host3
        container_name: as101h-Ethereum-POS-4-10.101.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_101_inet1:
                ipv4_address: 10.101.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "101"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-4"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "4"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.101.1.71/24"

        environment:
            - CONTAINER_NAME=as101h-Ethereum-POS-4-10.101.1.71

    hnode_101_host4:
        build: ./hnode_101_host4
        container_name: as101h-Ethereum-POS-5-10.101.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_101_inet1:
                ipv4_address: 10.101.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "101"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-5"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "5"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.101.1.72/24"

        environment:
            - CONTAINER_NAME=as101h-Ethereum-POS-5-10.101.1.72

    hnode_101_host5:
        build: ./hnode_101_host5
        container_name: as101h-Ethereum-POS-6-10.101.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_101_inet1:
                ipv4_address: 10.101.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "101"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-6"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "6"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.101.1.73/24"

        environment:
            - CONTAINER_NAME=as101h-Ethereum-POS-6-10.101.1.73

    hnode_102_host3:
        build: ./hnode_102_host3
        container_name: as102h-Ethereum-POS-13-10.102.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_102_inet1:
                ipv4_address: 10.102.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "102"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-13"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "13"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.102.1.71/24"

        environment:
            - CONTAINER_NAME=as102h-Ethereum-POS-13-10.102.1.71

    hnode_102_host4:
        build: ./hnode_102_host4
        container_name: as102h-Ethereum-POS-14-10.102.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_102_inet1:
                ipv4_address: 10.102.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "102"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-14"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "14"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.102.1.72/24"

        environment:
            - CONTAINER_NAME=as102h-Ethereum-POS-14-10.102.1.72

    hnode_102_host5:
        build: ./hnode_102_host5
        container_name: as102h-Ethereum-POS-15-10.102.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_102_inet1:
                ipv4_address: 10.102.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "102"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-15"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "15"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.102.1.73/24"

        environment:
            - CONTAINER_NAME=as102h-Ethereum-POS-15-10.102.1.73

    hnode_103_host3:
        build: ./hnode_103_host3
        container_name: as103h-Ethereum-POS-22-10.103.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_103_inet1:
                ipv4_address: 10.103.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "103"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-22"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "22"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.103.1.71/24"

        environment:
            - CONTAINER_NAME=as103h-Ethereum-POS-22-10.103.1.71

    hnode_103_host4:
        build: ./hnode_103_host4
        container_name: as103h-Ethereum-POS-23-10.103.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_103_inet1:
                ipv4_address: 10.103.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "103"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-23"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "23"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.103.1.72/24"

        environment:
            - CONTAINER_NAME=as103h-Ethereum-POS-23-10.103.1.72

    hnode_103_host5:
        build: ./hnode_103_host5
        container_name: as103h-Ethereum-POS-24-10.103.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_103_inet1:
                ipv4_address: 10.103.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "103"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-24"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "24"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.103.1.73/24"

        environment:
            - CONTAINER_NAME=as103h-Ethereum-POS-24-10.103.1.73

    hnode_104_host3:
        build: ./hnode_104_host3
        container_name: as104h-Ethereum-POS-31-10.104.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_104_inet1:
                ipv4_address: 10.104.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "104"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-31"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "31"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.104.1.71/24"

        environment:
            - CONTAINER_NAME=as104h-Ethereum-POS-31-10.104.1.71

    hnode_104_host4:
        build: ./hnode_104_host4
        container_name: as104h-Ethereum-POS-32-10.104.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_104_inet1:
                ipv4_address: 10.104.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "104"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-32"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "32"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.104.1.72/24"

        environment:
            - CONTAINER_NAME=as104h-Ethereum-POS-32-10.104.1.72

    hnode_104_host5:
        build: ./hnode_104_host5
        container_name: as104h-Ethereum-POS-33-10.104.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_104_inet1:
                ipv4_address: 10.104.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "104"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-33"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "33"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.104.1.73/24"

        environment:
            - CONTAINER_NAME=as104h-Ethereum-POS-33-10.104.1.73

    hnode_105_host3:
        build: ./hnode_105_host3
        container_name: as105h-Ethereum-POS-40-10.105.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_105_inet1:
                ipv4_address: 10.105.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "105"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-40"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "40"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.105.1.71/24"

        environment:
            - CONTAINER_NAME=as105h-Ethereum-POS-40-10.105.1.71

    hnode_105_host4:
        build: ./hnode_105_host4
        container_name: as105h-Ethereum-POS-41-10.105.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_105_inet1:
                ipv4_address: 10.105.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "105"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-41"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "41"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.105.1.72/24"

        environment:
            - CONTAINER_NAME=as105h-Ethereum-POS-41-10.105.1.72

    hnode_105_host5:
        build: ./hnode_105_host5
        container_name: as105h-Ethereum-POS-42-10.105.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_105_inet1:
                ipv4_address: 10.105.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "105"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-42"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "42"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.105.1.73/24"

        environment:
            - CONTAINER_NAME=as105h-Ethereum-POS-42-10.105.1.73

    hnode_106_host3:
        build: ./hnode_106_host3
        container_name: as106h-Ethereum-POS-49-10.106.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_106_inet1:
                ipv4_address: 10.106.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "106"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-49"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "49"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.106.1.71/24"

        environment:
            - CONTAINER_NAME=as106h-Ethereum-POS-49-10.106.1.71

    hnode_106_host4:
        build: ./hnode_106_host4
        container_name: as106h-Ethereum-POS-50-10.106.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_106_inet1:
                ipv4_address: 10.106.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "106"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-50"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "50"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.106.1.72/24"

        environment:
            - CONTAINER_NAME=as106h-Ethereum-POS-50-10.106.1.72

    hnode_106_host5:
        build: ./hnode_106_host5
        container_name: as106h-Ethereum-POS-51-10.106.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_106_inet1:
                ipv4_address: 10.106.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "106"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-51"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "51"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.106.1.73/24"

        environment:
            - CONTAINER_NAME=as106h-Ethereum-POS-51-10.106.1.73

    hnode_107_host3:
        build: ./hnode_107_host3
        container_name: as107h-Ethereum-POS-58-10.107.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_107_inet1:
                ipv4_address: 10.107.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "107"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-58"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "58"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.107.1.71/24"

        environment:
            - CONTAINER_NAME=as107h-Ethereum-POS-58-10.107.1.71

    hnode_107_host4:
        build: ./hnode_107_host4
        container_name: as107h-Ethereum-POS-59-10.107.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_107_inet1:
                ipv4_address: 10.107.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "107"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-59"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "59"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.107.1.72/24"

        environment:
            - CONTAINER_NAME=as107h-Ethereum-POS-59-10.107.1.72

    hnode_107_host5:
        build: ./hnode_107_host5
        container_name: as107h-Ethereum-POS-60-10.107.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_107_inet1:
                ipv4_address: 10.107.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "107"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-60"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "60"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.107.1.73/24"

        environment:
            - CONTAINER_NAME=as107h-Ethereum-POS-60-10.107.1.73

    hnode_108_host3:
        build: ./hnode_108_host3
        container_name: as108h-Ethereum-POS-67-10.108.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_108_inet1:
                ipv4_address: 10.108.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "108"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-67"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "67"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.108.1.71/24"

        environment:
            - CONTAINER_NAME=as108h-Ethereum-POS-67-10.108.1.71

    hnode_108_host4:
        build: ./hnode_108_host4
        container_name: as108h-Ethereum-POS-68-10.108.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_108_inet1:
                ipv4_address: 10.108.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "108"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-68"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "68"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.108.1.72/24"

        environment:
            - CONTAINER_NAME=as108h-Ethereum-POS-68-10.108.1.72

    hnode_108_host5:
        build: ./hnode_108_host5
        container_name: as108h-Ethereum-POS-69-10.108.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_108_inet1:
                ipv4_address: 10.108.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "108"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-69"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "69"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.108.1.73/24"

        environment:
            - CONTAINER_NAME=as108h-Ethereum-POS-69-10.108.1.73

    hnode_109_host3:
        build: ./hnode_109_host3
        container_name: as109h-Ethereum-POS-76-10.109.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_109_inet1:
                ipv4_address: 10.109.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "109"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-76"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "76"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.109.1.71/24"

        environment:
            - CONTAINER_NAME=as109h-Ethereum-POS-76-10.109.1.71

    hnode_109_host4:
        build: ./hnode_109_host4
        container_name: as109h-Ethereum-POS-77-10.109.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_109_inet1:
                ipv4_address: 10.109.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "109"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-77"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "77"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.109.1.72/24"

        environment:
            - CONTAINER_NAME=as109h-Ethereum-POS-77-10.109.1.72

    hnode_109_host5:
        build: ./hnode_109_host5
        container_name: as109h-Ethereum-POS-78-10.109.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_109_inet1:
                ipv4_address: 10.109.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "109"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-78"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "78"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.109.1.73/24"

        environment:
            - CONTAINER_NAME=as109h-Ethereum-POS-78-10.109.1.73

    hnode_110_host3:
        build: ./hnode_110_host3
        container_name: as110h-Ethereum-POS-85-10.110.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_110_inet1:
                ipv4_address: 10.110.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "110"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-85"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "85"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.110.1.71/24"

        environment:
            - CONTAINER_NAME=as110h-Ethereum-POS-85-10.110.1.71

    hnode_110_host4:
        build: ./hnode_110_host4
        container_name: as110h-Ethereum-POS-86-10.110.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_110_inet1:
                ipv4_address: 10.110.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "110"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-86"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "86"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.110.1.72/24"

        environment:
            - CONTAINER_NAME=as110h-Ethereum-POS-86-10.110.1.72

    hnode_110_host5:
        build: ./hnode_110_host5
        container_name: as110h-Ethereum-POS-87-10.110.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_110_inet1:
                ipv4_address: 10.110.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "110"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-87"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "87"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.110.1.73/24"

        environment:
            - CONTAINER_NAME=as110h-Ethereum-POS-87-10.110.1.73

    hnode_111_host3:
        build: ./hnode_111_host3
        container_name: as111h-Ethereum-POS-94-10.111.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_111_inet1:
                ipv4_address: 10.111.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "111"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-94"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "94"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.111.1.71/24"

        environment:
            - CONTAINER_NAME=as111h-Ethereum-POS-94-10.111.1.71

    hnode_111_host4:
        build: ./hnode_111_host4
        container_name: as111h-Ethereum-POS-95-10.111.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_111_inet1:
                ipv4_address: 10.111.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "111"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-95"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "95"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.111.1.72/24"

        environment:
            - CONTAINER_NAME=as111h-Ethereum-POS-95-10.111.1.72

    hnode_111_host5:
        build: ./hnode_111_host5
        container_name: as111h-Ethereum-POS-96-10.111.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_111_inet1:
                ipv4_address: 10.111.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "111"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-96"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "96"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.111.1.73/24"

        environment:
            - CONTAINER_NAME=as111h-Ethereum-POS-96-10.111.1.73

    hnode_112_host3:
        build: ./hnode_112_host3
        container_name: as112h-Ethereum-POS-103-10.112.1.71
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_112_inet1:
                ipv4_address: 10.112.1.71


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "112"
            org.seedsecuritylabs.seedemu.meta.nodename: "host3"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-103"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "103"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.112.1.71/24"

        environment:
            - CONTAINER_NAME=as112h-Ethereum-POS-103-10.112.1.71

    hnode_112_host4:
        build: ./hnode_112_host4
        container_name: as112h-Ethereum-POS-104-10.112.1.72
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_112_inet1:
                ipv4_address: 10.112.1.72


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "112"
            org.seedsecuritylabs.seedemu.meta.nodename: "host4"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-104"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "104"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.112.1.72/24"

        environment:
            - CONTAINER_NAME=as112h-Ethereum-POS-104-10.112.1.72

    hnode_112_host5:
        build: ./hnode_112_host5
        container_name: as112h-Ethereum-POS-105-10.112.1.73
        depends_on:
            - f1d53a66de3c35d8a921558f3b4bdbbd
        cap_add:
            - ALL

        privileged: true
        networks:
            eth_docker_network-100_net_112_inet1:
                ipv4_address: 10.112.1.73


        labels:
            org.seedsecuritylabs.seedemu.meta.asn: "112"
            org.seedsecuritylabs.seedemu.meta.nodename: "host5"
            org.seedsecuritylabs.seedemu.meta.role: "Host"
            org.seedsecuritylabs.seedemu.meta.displayname: "Ethereum-POS-105"
            org.seedsecuritylabs.seedemu.meta.class: "[\"EthereumService\"]"
            org.seedsecuritylabs.seedemu.meta.ethereum.node_id: "105"
            org.seedsecuritylabs.seedemu.meta.ethereum.consensus: "POS"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_name: "posCurrentEnhancedNet"
            org.seedsecuritylabs.seedemu.meta.ethereum.chain_id: "1337"
            org.seedsecuritylabs.seedemu.meta.ethereum.role: "[\"validator_at_genesis\"\
                , \"miner\"]"
            org.seedsecuritylabs.seedemu.meta.net.0.name: "inet1"
            org.seedsecuritylabs.seedemu.meta.net.0.address: "10.112.1.73/24"

        environment:
            - CONTAINER_NAME=as112h-Ethereum-POS-105-10.112.1.73

networks:
    eth_docker_network-100_net_101_inet1:
        external: true
    eth_docker_network-100_net_102_inet1:
        external: true
    eth_docker_network-100_net_103_inet1:
        external: true
    eth_docker_network-100_net_104_inet1:
        external: true
    eth_docker_network-100_net_105_inet1:
        external: true
    eth_docker_network-100_net_106_inet1:
        external: true
    eth_docker_network-100_net_107_inet1:
        external: true
    eth_docker_network-100_net_108_inet1:
        external: true
    eth_docker_network-100_net_109_inet1:
        external: true
    eth_docker_network-100_net_110_inet1:
        external: true
    eth_docker_network-100_net_111_inet1:
        external: true
    eth_docker_network-100_net_112_inet1:
        external: true
