#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.101.0.254 dev inet0
lcli generate-bootnode-enr --ip 10.101.0.72 --udp-port 30305 --tcp-port 30305 --genesis-fork-version 0x42424242 --output-dir /local-testnet/bootnode
mkdir /local-testnet/testnet
bootnode_enr=`cat /local-testnet/bootnode/enr.dat`
echo "- $bootnode_enr" > /local-testnet/testnet/boot_enr.yaml
cp /tmp/config.yaml /local-testnet/testnet/config.yaml
until curl --http0.9 -sHf http://10.101.0.73:8545 > /dev/null; do {
        echo "beacon-setup-node: geth node is not ready, waiting..."
        sleep 3
        let count++
        [ $count -gt 60 ] && {
            echo "beacon-setup-node: geth node connection failed too many times, skipping."
            ok=false
            break
        }
    }; done

while true; do {
    blockNumber=`curl --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://10.101.0.73:8545 | jq -r '.result' | cut -d 'x' -f 2`
    echo "current blockNumber :" $(( 16#$blockNumber ))
    if [ $(( 16#$blockNumber )) -gt 5 ]
    then
            break
    fi
    sleep 3
}; done

while true; do {
    lcli deploy-deposit-contract --eth1-http http://10.101.0.73:8545 --confirmations 1 --validator-count 106 > contract_address.txt
    CONTRACT_ADDRESS=`head -1 contract_address.txt | cut -d '"' -f 2`
    if [[ $CONTRACT_ADDRESS = 0x* ]]; then
        break
    fi
    echo "beacon-setup-node: Waiting for Validator Deposit..."
    sleep 10

}; done

lcli insecure-validators --count 106 --base-dir /local-testnet/ --node-count 106
GENESIS_TIME=`date +%s`
CONTRACT_ADDRESS=`head -1 contract_address.txt | cut -d '"' -f 2`
echo 'DEPOSIT_CONTRACT_ADDRESS: "'$CONTRACT_ADDRESS'"' >> /local-testnet/testnet/config.yaml
echo 'MIN_GENESIS_TIME: "'$GENESIS_TIME'"' >> /local-testnet/testnet/config.yaml
echo '3' > /local-testnet/testnet/deploy_block.txt
lcli interop-genesis --spec mainnet --genesis-time $GENESIS_TIME --testnet-dir /local-testnet/testnet 106
chmod +x /tmp/prepare_resource.sh
/tmp/prepare_resource.sh
python3 /local-testnet/beacon_bootnode_http_server.py &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter
sysctl -w net.ipv4.ip_forward=1 > /dev/null 2>&1
sysctl -w net.ipv4.udp_rmem_min=4000 > /dev/null 2>&1
sysctl -w net.ipv4.udp_wmem_min=4000 > /dev/null 2>&1
sysctl -w net.ipv4.tcp_rmem="4096 131072 6291456" > /dev/null 2>&1
sysctl -w net.ipv4.tcp_wmem="4096 16384 4194304" > /dev/null 2>&1
tail -f /dev/null

