#!/bin/bash
while read -r node; do {
    let count=0
    ok=true
    validator=false
    until curl --http0.9 -sHf http://$node/testnet > /dev/null; do {
        echo "eth: beacon-setup node $node not ready, waiting..."
        sleep 10
        let count++
        [ $count -gt 60 ] && {
            echo "eth: connection to beacon-setup node $node failed too many times, skipping."
            ok=false
            break
        }
    }; done
    ($ok) && {
        validator=true
        bootnode=false
        ($validator) && {
            curl --http0.9 -s http://$node/eth-74 > /tmp/eth.tar.gz
            tar -xzvf /tmp/eth.tar.gz -C /tmp
        }
        ($bootnode) && {
            curl --http0.9 -s http://$node/bootnode > /tmp/bootnode.tar.gz
            tar -xzvf /tmp/bootnode.tar.gz -C /tmp
        }
        curl --http0.9 -s http://$node/testnet > /tmp/testnet.tar.gz
        tar -xzvf /tmp/testnet.tar.gz -C /tmp
        
        lighthouse --debug-level info bn --datadir /tmp/local-testnet/eth-74 --testnet-dir /tmp/local-testnet/testnet --enable-private-discovery --staking --enr-address 10.109.0.72  --enr-udp-port 9000 --enr-tcp-port 9000 --port 9000 --http-address 10.109.0.72 --http-port 8000 --http-allow-origin "*" --disable-packet-filter --target-peers 5 --execution-endpoint http://localhost:8551 --execution-jwt /tmp/jwt.hex &
        
        
        
        lighthouse --debug-level info vc --datadir /tmp/local-testnet/eth-74 --testnet-dir /tmp/local-testnet/testnet --init-slashing-protection --beacon-nodes http://10.109.0.72:8000 --suggested-fee-recipient 0x36Cbb6bEE031ceeA490b0F7B4c918d41693a1c88 --http --http-address 0.0.0.0 --http-allow-origin "*" --unencrypted-http-transport &
    }
}; done < /tmp/beacon-setup-node



